### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bertux** [pchain-org/pchain#34]
how to fix this build error ?

ubuntu@bert-pchain:~/pchain$ ./build.sh 
/home/ubuntu/pchain
/home/ubuntu/pchain
/home/ubuntu/pchain/src/github.com/pchain
go build -o /home/ubuntu/pchain/bin/pchain ./cmd/
# github.com/pchain/vendor/github.com/ethereum/go-ethereum/consensus/tendermint/consensus
vendor/github.com/ethereum/go-ethereum/consensus/tendermint/consensus/state.go:1885:34: invalid UTF-8 encoding
Makefile:3: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by fanbsb** [comment]
We just commit the fix 4358f99117fb559949c739fcda8ad35ee9e63d37 for utf-8 encoding error. This is by mistake.
